# Generated by Django 3.0.5 on 2020-04-29 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_facturadet_facturaenc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facturadet',
            options={'permissions': [('sup_caja_facturadet', 'Permisos de supervisor de caja Detalle')], 'verbose_name': 'Detalle factura', 'verbose_name_plural': 'Detalles facturas'},
        ),
        migrations.AlterModelOptions(
            name='facturaenc',
            options={'permissions': [('sup_caja_facturaenc', 'Permisos de supervisor de caja encabezado')], 'verbose_name': 'Encabezado factura', 'verbose_name_plural': 'Encabezado Facturas'},
        ),
    ]
